export default {
  arrowDown: "heroicons-solid:arrow-down",
  arrowLeft: "heroicons-solid:arrow-left",
  arrowRight: "heroicons-solid:arrow-right",
  arrowUp: "heroicons-solid:arrow-up",
  chevronDoubleLeft: "heroicons-solid:chevron-double-left",
  chevronDoubleRight: "heroicons-solid:chevron-double-right",
  chevronDown: "heroicons-solid:chevron-down",
  chevronLeft: "heroicons-solid:chevron-left",
  chevronRight: "heroicons-solid:chevron-right",
  chevronUp: "heroicons-solid:chevron-up",
  close: "heroicons-solid:x",
  dark: "heroicons-solid:moon",
  image: "heroicons-solid:photo",
  light: "heroicons-solid:sun",
  loading: "heroicons-solid:arrow-path",
  menu: "heroicons-solid:menu",
  search: "heroicons-solid:search",
  system: "heroicons-solid:computer-desktop",
  user: "heroicons-solid:user",
  warning: "heroicons-solid:exclamation-triangle",
};
