export default {
  arrowDown: "heroicons-outline:arrow-down",
  arrowLeft: "heroicons-outline:arrow-left",
  arrowRight: "heroicons-outline:arrow-right",
  arrowUp: "heroicons-outline:arrow-up",
  chevronDoubleLeft: "heroicons-outline:chevron-double-left",
  chevronDoubleRight: "heroicons-outline:chevron-double-right",
  chevronDown: "heroicons-outline:chevron-down",
  chevronLeft: "heroicons-outline:chevron-left",
  chevronRight: "heroicons-outline:chevron-right",
  chevronUp: "heroicons-outline:chevron-up",
  close: "heroicons-outline:x",
  dark: "heroicons-outline:moon",
  image: "heroicons-outline:photo",
  light: "heroicons-outline:sun",
  loading: "heroicons-outline:arrow-path",
  menu: "heroicons-outline:menu",
  search: "heroicons-outline:search",
  system: "heroicons-outline:desktop-computer",
  user: "heroicons-outline:user",
  warning: "heroicons-outline:exclamation-triangle",
};
