export default {
  arrowDown: "hugeicons:arrow-down-02",
  arrowLeft: "hugeicons:arrow-left-02",
  arrowRight: "hugeicons:arrow-right-02",
  arrowUp: "hugeicons:arrow-up-02",
  chevronDoubleLeft: "hugeicons:arrow-left-double",
  chevronDoubleRight: "hugeicons:arrow-right-double",
  chevronDown: "hugeicons:arrow-down-01",
  chevronLeft: "hugeicons:arrow-left-01",
  chevronRight: "hugeicons:arrow-right-01",
  chevronUp: "hugeicons:arrow-up-01",
  close: "hugeicons:cancel-01",
  dark: "hugeicons:moon-02",
  image: "hugeicons:image-01",
  light: "hugeicons:sun-02",
  loading: "hugeicons:refresh",
  menu: "hugeicons:menu-01",
  search: "hugeicons:search-01",
  system: "hugeicons:computer",
  user: "hugeicons:user",
  warning: "hugeicons:alert-01",
};
