export default {
  arrowDown: "iconoir:arrow-down",
  arrowLeft: "iconoir:arrow-left",
  arrowRight: "iconoir:arrow-right",
  arrowUp: "iconoir:arrow-up",
  chevronDoubleLeft: "iconoir:nav-arrow-left",
  chevronDoubleRight: "iconoir:nav-arrow-right",
  chevronDown: "iconoir:nav-arrow-down",
  chevronLeft: "iconoir:nav-arrow-left",
  chevronRight: "iconoir:nav-arrow-right",
  chevronUp: "iconoir:nav-arrow-up",
  close: "iconoir:xmark",
  dark: "iconoir:half-moon",
  image: "iconoir:media-image",
  light: "iconoir:sun-light",
  loading: "iconoir:refresh",
  menu: "iconoir:menu",
  search: "iconoir:search",
  system: "iconoir:monitor",
  user: "iconoir:user",
  warning: "iconoir:warning-triangle",
};
