export default {
  arrowDown: "lucide:arrow-down",
  arrowLeft: "lucide:arrow-left",
  arrowRight: "lucide:arrow-right",
  arrowUp: "lucide:arrow-up",
  chevronDoubleLeft: "lucide:chevrons-left",
  chevronDoubleRight: "lucide:chevrons-right",
  chevronDown: "lucide:chevron-down",
  chevronLeft: "lucide:chevron-left",
  chevronRight: "lucide:chevron-right",
  chevronUp: "lucide:chevron-up",
  close: "lucide:x",
  dark: "lucide:moon",
  image: "lucide:image",
  light: "lucide:sun",
  loading: "lucide:loader-circle",
  menu: "lucide:menu",
  search: "lucide:search",
  system: "lucide:monitor",
  user: "lucide:user",
  warning: "lucide:triangle-alert",
};
