export default {
  arrowDown: "material-symbols:arrow-downward",
  arrowLeft: "material-symbols:arrow-back",
  arrowRight: "material-symbols:arrow-forward",
  arrowUp: "material-symbols:arrow-upward",
  chevronDoubleLeft: "material-symbols:keyboard-double-arrow-left",
  chevronDoubleRight: "material-symbols:keyboard-double-arrow-right",
  chevronDown: "material-symbols:keyboard-arrow-down",
  chevronLeft: "material-symbols:keyboard-arrow-left",
  chevronRight: "material-symbols:keyboard-arrow-right",
  chevronUp: "material-symbols:keyboard-arrow-up",
  close: "material-symbols:close",
  dark: "material-symbols:dark-mode",
  image: "material-symbols:image",
  light: "material-symbols:light-mode",
  loading: "material-symbols:progress-activity",
  menu: "material-symbols:menu",
  search: "material-symbols:search",
  system: "material-symbols:desktop-windows",
  user: "material-symbols:person",
  warning: "material-symbols:warning",
};
