export default {
  arrowDown: "mdi:arrow-down",
  arrowLeft: "mdi:arrow-left",
  arrowRight: "mdi:arrow-right",
  arrowUp: "mdi:arrow-up",
  chevronDoubleLeft: "mdi:chevron-double-left",
  chevronDoubleRight: "mdi:chevron-double-right",
  chevronDown: "mdi:chevron-down",
  chevronLeft: "mdi:chevron-left",
  chevronRight: "mdi:chevron-right",
  chevronUp: "mdi:chevron-up",
  close: "mdi:close",
  dark: "mdi:weather-night",
  image: "mdi:image-outline",
  light: "mdi:white-balance-sunny",
  loading: "mdi:loading",
  menu: "mdi:menu",
  search: "mdi:magnify",
  system: "mdi:monitor",
  user: "mdi:account-outline",
  warning: "mdi:alert-outline",
};
