export default {
  arrowDown: "mingcute:arrow-down-line",
  arrowLeft: "mingcute:arrow-left-line",
  arrowRight: "mingcute:arrow-right-line",
  arrowUp: "mingcute:arrow-up-line",
  chevronDoubleLeft: "mingcute:left-line",
  chevronDoubleRight: "mingcute:right-line",
  chevronDown: "mingcute:down-line",
  chevronLeft: "mingcute:left-line",
  chevronRight: "mingcute:right-line",
  chevronUp: "mingcute:up-line",
  close: "mingcute:close-line",
  dark: "mingcute:moon-line",
  image: "mingcute:pic-line",
  light: "mingcute:sun-line",
  loading: "mingcute:loading-line",
  menu: "mingcute:menu-line",
  search: "mingcute:search-line",
  system: "mingcute:computer-line",
  user: "mingcute:user-line",
  warning: "mingcute:warning-line",
};
