export default {
  arrowDown: "ph:arrow-down",
  arrowLeft: "ph:arrow-left",
  arrowRight: "ph:arrow-right",
  arrowUp: "ph:arrow-up",
  chevronDoubleLeft: "ph:caret-double-left",
  chevronDoubleRight: "ph:caret-double-right",
  chevronDown: "ph:caret-down",
  chevronLeft: "ph:caret-left",
  chevronRight: "ph:caret-right",
  chevronUp: "ph:caret-up",
  close: "ph:x",
  dark: "ph:moon",
  image: "ph:image",
  light: "ph:sun",
  loading: "ph:spinner",
  menu: "ph:list",
  search: "ph:magnifying-glass",
  system: "ph:monitor",
  user: "ph:user",
  warning: "ph:warning",
};
