export default {
  arrowDown: "tabler:arrow-down",
  arrowLeft: "tabler:arrow-left",
  arrowRight: "tabler:arrow-right",
  arrowUp: "tabler:arrow-up",
  chevronDoubleLeft: "tabler:chevrons-left",
  chevronDoubleRight: "tabler:chevrons-right",
  chevronDown: "tabler:chevron-down",
  chevronLeft: "tabler:chevron-left",
  chevronRight: "tabler:chevron-right",
  chevronUp: "tabler:chevron-up",
  close: "tabler:x",
  dark: "tabler:moon",
  image: "tabler:photo",
  light: "tabler:sun",
  loading: "tabler:loader-2",
  menu: "tabler:menu",
  search: "tabler:search",
  system: "tabler:device-desktop",
  user: "tabler:user",
  warning: "tabler:alert-triangle",
};
